#!/usr/bin/env python3
"""Final comprehensive translation sweep — all remaining strings across all 41 pages."""
import re

T = {
  # ── LABELS / HEADINGS ──
  "General": {"fr":"Général","de":"Allgemein","lb":"Allgemeng","nl":"Algemeen"},
  "Safety": {"fr":"Sécurité","de":"Sicherheit","lb":"Sécherheet","nl":"Veiligheid"},
  "Booking": {"fr":"Réservation","de":"Buchung","lb":"Buchung","nl":"Boeking"},
  "Duration": {"fr":"Durée","de":"Dauer","lb":"Dauer","nl":"Duur"},
  "Discount": {"fr":"Réduction","de":"Rabatt","lb":"Rabatt","nl":"Korting"},
  "Discovery": {"fr":"Découverte","de":"Entdeckung","lb":"Entdeckung","nl":"Ontdekking"},
  "Fitness": {"fr":"Fitness","de":"Fitness","lb":"Fitness","nl":"Fitness"},
  "Supervision": {"fr":"Supervision","de":"Überwachung","lb":"Iwwerwaachung","nl":"Toezicht"},
  "Logistics": {"fr":"Logistique","de":"Logistik","lb":"Logistik","nl":"Logistiek"},
  "Tracking": {"fr":"Suivi","de":"Verfolgung","lb":"Verfolgung","nl":"Tracking"},
  "Loyalty": {"fr":"Fidélité","de":"Treue","lb":"Loyalitéit","nl":"Loyaliteit"},
  "Education": {"fr":"Éducation","de":"Bildung","lb":"Bildung","nl":"Onderwijs"},
  "Engineering": {"fr":"Ingénierie","de":"Ingenieurwesen","lb":"Ingenieurwesen","nl":"Techniek"},
  "Marketing assets": {"fr":"Matériaux marketing","de":"Marketing-Materialien","lb":"Marketing-Materialien","nl":"Marketingmaterialen"},
  "Parking": {"fr":"Parking","de":"Parken","lb":"Parken","nl":"Parkeren"},
  "Participants": {"fr":"Participants","de":"Teilnehmer","lb":"Participanten","nl":"Deelnemers"},
  "Photography": {"fr":"Photographie","de":"Fotografie","lb":"Fotografie","nl":"Fotografie"},
  "Speed": {"fr":"Vitesse","de":"Geschwindigkeit","lb":"Vitesse","nl":"Snelheid"},
  "Transitions": {"fr":"Transitions","de":"Übergänge","lb":"Transitiounen","nl":"Overgangen"},
  "Minimum Age": {"fr":"Âge minimum","de":"Mindestalter","lb":"Mindestalter","nl":"Minimumleeftijd"},
  "Max Weight": {"fr":"Poids maximum","de":"Maximales Gewicht","lb":"Maximalgewiicht","nl":"Maximaal gewicht"},
  "Tunnel Height": {"fr":"Hauteur du tunnel","de":"Tunnelhöhe","lb":"Tunnelhéicht","nl":"Tunnelhoogte"},
  "Tunnel Height": {"fr":"Hauteur du tunnel","de":"Tunnelhöhe","lb":"Tunnelhéicht","nl":"Tunnelhoogte"},
  "Max Airspeed (km/h)": {"fr":"Vitesse d'air max (km/h)","de":"Max. Luftgeschwindigkeit (km/h)","lb":"Max Loftgeschwindegkeet (km/h)","nl":"Max luchtsnelheid (km/h)"},
  "Electric Motors": {"fr":"Moteurs électriques","de":"Elektromotoren","lb":"Elektromotoren","nl":"Elektromotoren"},
  "Flight time": {"fr":"Temps de vol","de":"Flugzeit","lb":"Fluchzäit","nl":"Vluchtijd"},
  "Meeting room": {"fr":"Salle de réunion","de":"Besprechungsraum","lb":"Bespriechungsraum","nl":"Vergaderzaal"},
  "Group size": {"fr":"Taille du groupe","de":"Gruppengröße","lb":"Grupp-Gréisst","nl":"Groepsgrootte"},
  "Group Size": {"fr":"Taille du groupe","de":"Gruppengröße","lb":"Grupp-Gréisst","nl":"Groepsgrootte"},
  "Price per Person": {"fr":"Prix par personne","de":"Preis pro Person","lb":"Präis pro Persoun","nl":"Prijs per persoon"},
  "Level Required": {"fr":"Niveau requis","de":"Erforderliches Niveau","lb":"Erfuerderlecht Niveau","nl":"Vereist niveau"},
  "Instructor Coverage": {"fr":"Couverture instructeur","de":"Instruktorenabdeckung","lb":"Instrukteursdeckung","nl":"Instructeursdekking"},
  "Minimum Age": {"fr":"Âge minimum","de":"Mindestalter","lb":"Mindestalter","nl":"Minimumleeftijd"},
  "Combined Tunnel Hours": {"fr":"Heures de tunnel combinées","de":"Kombinierte Tunnelstunden","lb":"Kombinéiert Tunnelstonne","nl":"Gecombineerde tunneluren"},
  "Languages": {"fr":"Langues","de":"Sprachen","lb":"Sprooche","nl":"Talen"},
  "Video system": {"fr":"Système vidéo","de":"Videosystem","lb":"Videosystem","nl":"Videosysteem"},
  "Debrief room": {"fr":"Salle de débriefing","de":"Debriefing-Raum","lb":"Debriefing-Raum","nl":"Debriefingkamer"},
  "Observer capacity": {"fr":"Capacité observateurs","de":"Zuschauerkapazität","lb":"Zuschauerkapazitéit","nl":"Toeschouwercapaciteit"},
  "Video Debrief": {"fr":"Débriefing vidéo","de":"Video-Debriefing","lb":"Video-Debriefing","nl":"Videodebriefing"},
  "Motors": {"fr":"Moteurs","de":"Motoren","lb":"Motoren","nl":"Motoren"},
  "Metres height": {"fr":"Mètres de hauteur","de":"Meter Höhe","lb":"Meter Héicht","nl":"Meter hoogte"},
  "Good fit": {"fr":"Convient","de":"Geeignet","lb":"Gëeegent","nl":"Geschikt"},
  "Not a fit": {"fr":"Ne convient pas","de":"Nicht geeignet","lb":"Net gëeegent","nl":"Niet geschikt"},
  "Parents": {"fr":"Parents","de":"Eltern","lb":"Elteren","nl":"Ouders"},
  "Custom": {"fr":"Personnalisé","de":"Individuell","lb":"Personaliséiert","nl":"Aangepast"},
  "Indoor": {"fr":"Indoor","de":"Indoor","lb":"Indoor","nl":"Indoor"},
  "Outdoor": {"fr":"Outdoor","de":"Outdoor","lb":"Outdoor","nl":"Outdoor"},
  "Other": {"fr":"Autre","de":"Sonstiges","lb":"Aneres","nl":"Overig"},
  "Media": {"fr":"Médias","de":"Medien","lb":"Medien","nl":"Media"},
  "Pathway": {"fr":"Parcours","de":"Weg","lb":"Wee","nl":"Traject"},
  "Leaders": {"fr":"Responsables","de":"Leiter","lb":"Leader","nl":"Leiders"},
  "Full-time / Part-time": {"fr":"Temps plein / Temps partiel","de":"Vollzeit / Teilzeit","lb":"Vollzäit / Deelzäit","nl":"Voltijd / Deeltijd"},
  "In person": {"fr":"En personne","de":"Persönlich","lb":"Perséinlech","nl":"Persoonlijk"},
  "Not a simulation. The real thing.": {"fr":"Pas une simulation. La vraie chose.","de":"Keine Simulation. Das Echte.","lb":"Keng Simulatioun. Dat Echt.","nl":"Geen simulatie. Het echte."},
  "In the air.": {"fr":"Dans les airs.","de":"In der Luft.","lb":"An der Loft.","nl":"In de lucht."},
  "Not flying? You're still welcome.": {"fr":"Vous ne volez pas ? Vous êtes toujours les bienvenus.","de":"Fliegen Sie nicht? Sie sind trotzdem willkommen.","lb":"Fléit Dir net? Dir sidd trotzdem wëllkommen.","nl":"Vliegt u niet? U bent nog steeds welkom."},
  "The Bar": {"fr":"Le Bar","de":"Die Bar","lb":"D'Bar","nl":"De Bar"},
  "The Feeling": {"fr":"La sensation","de":"Das Gefühl","lb":"D'Gefill","nl":"Het gevoel"},
  "The Wind Tunnel": {"fr":"Le tunnel à vent","de":"Der Windkanal","lb":"Den Wandkanal","nl":"De windtunnel"},
  "The Daredevil": {"fr":"Le Casse-cou","de":"Der Draufgänger","lb":"Den Draufgänger","nl":"De Waagstuk"},
  "The Natural": {"fr":"Le Naturel","de":"Der Natürliche","lb":"Den Natierlechen","nl":"De Natuurtalent"},
  "The Team Player": {"fr":"Le Joueur d'équipe","de":"Der Teamplayer","lb":"Den Teamspiller","nl":"De Teamspeler"},
  "The Thinker": {"fr":"Le Penseur","de":"Der Denker","lb":"Den Denker","nl":"De Denker"},
  "What Kind of Flyer Are You?": {"fr":"Quel type de pilote êtes-vous ?","de":"Was für ein Flieger sind Sie?","lb":"Wat fir e Fléier sidd Dir?","nl":"Wat voor vlieger bent u?"},
  "Sky adventure": {"fr":"Aventure dans le ciel","de":"Himmelsabenteuer","lb":"Himmelssabenteuer","nl":"Luchtavontuur"},
  "Fitness seekers": {"fr":"Amateurs de fitness","de":"Fitnessinteressierte","lb":"Fitnessinteressierte","nl":"Fitnesspuristen"},
  "Mindful exercisers": {"fr":"Pratiquants conscients","de":"Achtsame Sporttreibende","lb":"Bewosst Sportler","nl":"Bewuste sporters"},
  "Injury recovery": {"fr":"Récupération après blessure","de":"Verletzungsrehabilitation","lb":"Verletzungsrehabilitatioun","nl":"Blessurerevalidatie"},
  "Pilates enthusiasts": {"fr":"Amateurs de Pilates","de":"Pilates-Enthusiasten","lb":"Pilates-Enthusiasten","nl":"Pilates enthousiastelingen"},
  "Interactive Museum": {"fr":"Musée interactif","de":"Interaktives Museum","lb":"Interaktiv Museum","nl":"Interactief museum"},
  "Sit Fly (Head Up)": {"fr":"Sit Fly (tête en haut)","de":"Sit Fly (Kopf oben)","lb":"Sit Fly (Kapp uewen)","nl":"Sit Fly (hoofd omhoog)"},
  "Head-Down": {"fr":"Tête en bas","de":"Kopf unten","lb":"Kapp ënnen","nl":"Hoofd omlaag"},
  "Neutral (Delta)": {"fr":"Neutre (Delta)","de":"Neutral (Delta)","lb":"Neutral (Delta)","nl":"Neutraal (Delta)"},
  "Dynamic (High-Speed)": {"fr":"Dynamique (haute vitesse)","de":"Dynamisch (Hochgeschwindigkeit)","lb":"Dynamesch (Héichgeschwindegkeet)","nl":"Dynamisch (hoge snelheid)"},
  "Session 1": {"fr":"Session 1","de":"Session 1","lb":"Session 1","nl":"Sessie 1"},
  "Session 2": {"fr":"Session 2","de":"Session 2","lb":"Session 2","nl":"Sessie 2"},
  "Sessions 3–5": {"fr":"Sessions 3–5","de":"Sessions 3–5","lb":"Sessionen 3–5","nl":"Sessies 3–5"},
  "Sessions 10+": {"fr":"Sessions 10+","de":"Sessions 10+","lb":"Sessionen 10+","nl":"Sessies 10+"},
  "Party packages": {"fr":"Forfaits fête","de":"Party-Pakete","lb":"Party-Pakete","nl":"Feestpakketten"},
  "Party Plus": {"fr":"Party Plus","de":"Party Plus","lb":"Party Plus","nl":"Party Plus"},
  "VIP Send-Off": {"fr":"Départ VIP","de":"VIP-Verabschiedung","lb":"VIP-Verabschiedung","nl":"VIP-uitzwaai"},
  "Standard party package": {"fr":"Forfait fête standard","de":"Standard-Party-Paket","lb":"Standard-Party-Pak","nl":"Standaard feestpakket"},
  "School Group": {"fr":"Groupe scolaire","de":"Schulgruppe","lb":"Schoulgrupp","nl":"Schoolgroep"},
  "Kids & Adults": {"fr":"Enfants & Adultes","de":"Kinder & Erwachsene","lb":"Kanner & Erwuessener","nl":"Kinderen & Volwassenen"},
  "Pro Events": {"fr":"Événements Pro","de":"Pro-Events","lb":"Pro-Eventer","nl":"Pro-evenementen"},
  "Pro Flying": {"fr":"Vol Pro","de":"Pro-Fliegen","lb":"Pro-Fléien","nl":"Pro-vliegen"},
  "Pro training": {"fr":"Entraînement pro","de":"Pro-Training","lb":"Pro-Training","nl":"Pro-training"},
  "Starter Block": {"fr":"Bloc Starter","de":"Starter-Block","lb":"Starter-Block","nl":"Starter-blok"},
  "Regular Block": {"fr":"Bloc Régulier","de":"Regular-Block","lb":"Regular-Block","nl":"Regulier blok"},
  "Dedicated Block": {"fr":"Bloc Dédié","de":"Dedicated-Block","lb":"Dedicated-Block","nl":"Dedicated blok"},
  "Elite Block": {"fr":"Bloc Élite","de":"Elite-Block","lb":"Elite-Block","nl":"Elite blok"},
  "Team Block": {"fr":"Bloc Équipe","de":"Team-Block","lb":"Team-Block","nl":"Team-blok"},
  "Foundations Pack": {"fr":"Pack Fondations","de":"Grundlagen-Paket","lb":"Fundament-Pak","nl":"Basispakket"},
  "Freefly Starter": {"fr":"Débutant Freefly","de":"Freefly-Starter","lb":"Freefly-Starter","nl":"Freefly beginner"},
  "Competition Prep": {"fr":"Préparation compétition","de":"Wettkampfvorbereitung","lb":"Wettkampfvirbereedung","nl":"Wedstrijdvoorbereiding"},
  "Custom Camp": {"fr":"Camp personnalisé","de":"Individuelles Camp","lb":"Personaliséiert Camp","nl":"Aangepast kamp"},
  "Weekend Camp": {"fr":"Camp week-end","de":"Wochenend-Camp","lb":"Wochenend-Camp","nl":"Weekendkamp"},
  "Tunnel time blocks": {"fr":"Blocs de temps tunnel","de":"Tunnel-Zeitblöcke","lb":"Tunnel-Zäitbléck","nl":"Tunneltijdblokken"},
  "SportFlyer": {"fr":"SportFlyer","de":"SportFlyer","lb":"SportFlyer","nl":"SportFlyer"},
  "Intermediate & above": {"fr":"Intermédiaire et au-delà","de":"Fortgeschrittene und mehr","lb":"Fortgeschratt a méi","nl":"Gevorderden en hoger"},
  "Intermediate/Advanced": {"fr":"Intermédiaire/Avancé","de":"Mittel/Fortgeschritten","lb":"Mëttel/Fortgeschratt","nl":"Gemiddeld/gevorderd"},
  "Freefly disciplines": {"fr":"Disciplines Freefly","de":"Freefly-Disziplinen","lb":"Freefly-Disziplinnen","nl":"Freefly-disciplines"},
  "Formation practice group": {"fr":"Groupe de pratique de formation","de":"Formationsübungsgruppe","lb":"Formatiounsübungsgrupp","nl":"Formatie oefengroep"},
  "Freestyle group": {"fr":"Groupe freestyle","de":"Freestyle-Gruppe","lb":"Freestyle-Grupp","nl":"Freestyle groep"},
  "Mixed intermediate": {"fr":"Mixte intermédiaire","de":"Gemischte Mittelstufe","lb":"Gemëscht Mëttelstuf","nl":"Gemengd gevorderd"},
  "Open (all levels, supervised)": {"fr":"Ouvert (tous niveaux, supervisé)","de":"Offen (alle Niveaus, beaufsichtigt)","lb":"Op (all Niveauen, iwwerwaacht)","nl":"Open (alle niveaus, onder toezicht)"},
  "Post-beginner flyers who want consistent practice": {"fr":"Pilotes post-débutants souhaitant une pratique régulière","de":"Fortgeschrittene Anfänger die regelmäßig üben möchten","lb":"Post-Ufänger Fléier déi regelméisseg wëllen üben","nl":"Post-beginners die consistent willen oefenen"},
  "The IBA tunnel certification system": {"fr":"Le système de certification tunnel IBA","de":"Das IBA-Tunnelzertifizierungssystem","lb":"D'IBA-Tunnelzertifizéierungssystem","nl":"Het IBA tunnel certificeringssysteem"},
  "Progression roadmap": {"fr":"Feuille de route de progression","de":"Fortschritts-Roadmap","lb":"Fortschrëtts-Roadmap","nl":"Progressie routekaart"},
  "Freefly Fundamentals": {"fr":"Fondamentaux du Freefly","de":"Freefly-Grundlagen","lb":"Freefly-Fundamentals","nl":"Freefly basisprincipes"},
  "The Luxfly loyalty programme runs through FidelityBox. Registration is free — just give your phone number at reception and it becomes your loyalty card. No app needed to sign up, no contracts, nothing to carry.": {"fr":"Le programme de fidélité Luxfly fonctionne via FidelityBox. L'inscription est gratuite — donnez simplement votre numéro de téléphone à la réception et il devient votre carte de fidélité. Pas d'appli nécessaire, pas de contrats, rien à porter.","de":"Das Luxfly-Treueprogramm läuft über FidelityBox. Die Anmeldung ist kostenlos — geben Sie einfach Ihre Telefonnummer an der Rezeption an, sie wird Ihre Treuekarte. Keine App nötig, keine Verträge, nichts zu tragen.","lb":"D'Luxfly Loyalitéitsprogramm leeft iwwer FidelityBox. D'Umeldung ass gratis — gitt einfach Är Telefonsnummer un der Rezeptioun an, si gëtt Är Loyalitéitskart. Keng App néideg, keng Kontrakter.","nl":"Het Luxfly loyaliteitsprogramma loopt via FidelityBox. Registratie is gratis — geef gewoon uw telefoonnummer bij de receptie en het wordt uw loyaliteitskaart. Geen app nodig, geen contracten."},
  "Track your points and available rewards at any time through the free FidelityBox app, available on iOS and Android.": {"fr":"Suivez vos points et récompenses disponibles à tout moment via l'appli FidelityBox gratuite, disponible sur iOS et Android.","de":"Verfolgen Sie Ihre Punkte und verfügbaren Prämien jederzeit über die kostenlose FidelityBox-App, erhältlich für iOS und Android.","lb":"Verfollegt Är Punkten a Präisser jidderzeits iwwer d'gratis FidelityBox-App, verfügbar fir iOS an Android.","nl":"Houd uw punten en beschikbare beloningen bij via de gratis FidelityBox-app, beschikbaar voor iOS en Android."},
  "You earn points automatically every time you visit. How you earn depends on your profile:": {"fr":"Vous gagnez des points automatiquement à chaque visite. Comment vous gagnez dépend de votre profil :","de":"Sie verdienen automatisch Punkte bei jedem Besuch. Wie Sie verdienen, hängt von Ihrem Profil ab:","lb":"Dir verdéngt automatesch Punkten bei all Besuch. Wéi Dir verdéngt hänkt vun Ärem Profil of:","nl":"U verdient automatisch punten bij elk bezoek. Hoe u verdient hangt af van uw profiel:"},
  "Start earning today.": {"fr":"Commencez à gagner aujourd'hui.","de":"Fangen Sie heute an zu verdienen.","lb":"Fänkt haut un ze verdéngen.","nl":"Begin vandaag met verdienen."},
  "Discount applied to your next visit — ask at reception when you reach the threshold.": {"fr":"Réduction appliquée à votre prochaine visite — demandez à la réception lorsque vous atteignez le seuil.","de":"Rabatt bei Ihrem nächsten Besuch — fragen Sie an der Rezeption, wenn Sie den Schwellenwert erreichen.","lb":"Rabatt op Ärer nächster Besuch — freet un der Rezeptioun wann Dir de Schwellenwäert erreecht.","nl":"Korting toegepast op uw volgende bezoek — vraag bij de receptie als u de drempel bereikt."},
  "Time never expires": {"fr":"Le temps n'expire jamais","de":"Zeit läuft nie ab","lb":"Zäit verfält ni","nl":"Tijd vervalt nooit"},
  "Reward minutes valid for 6 months": {"fr":"Minutes de récompense valables 6 mois","de":"Prämienminuten 6 Monate gültig","lb":"Prämienminutten 6 Méint gülteg","nl":"Beloningsminuten 6 maanden geldig"},
  "Partner support": {"fr":"Support partenaire","de":"Partner-Support","lb":"Partner-Support","nl":"Partnerondersteuning"},
  "Team perks": {"fr":"Avantages équipe","de":"Team-Vorteile","lb":"Team-Virdeeler","nl":"Teamvoordelen"},
  "Team events": {"fr":"Événements d'équipe","de":"Team-Events","lb":"Team-Eventer","nl":"Teamevenementen"},
  "Employee discount": {"fr":"Réduction employé","de":"Mitarbeiterrabatt","lb":"Mataarbechterrabatt","nl":"Personeelskorting"},
  "IBA certification sponsorship": {"fr":"Parrainage certification IBA","de":"IBA-Zertifizierungssponsoring","lb":"IBA-Zertifizéierungssponserung","nl":"IBA certificering sponsoring"},
  "Flexible hours — early morning access from 7am": {"fr":"Horaires flexibles — accès tôt le matin dès 7h","de":"Flexible Zeiten — frühmorgendlicher Zugang ab 7 Uhr","lb":"Flexibel Zäiten — fréimuergens Zougang ab 7 Auer","nl":"Flexibele uren — vroeg toegang vanaf 7 uur"},
  "Free tunnel time every month": {"fr":"Temps de tunnel gratuit chaque mois","de":"Kostenlose Tunnelzeit jeden Monat","lb":"Gratis Tunnelzäit all Mount","nl":"Gratis tunneltijd elke maand"},
  "National-level training, includes monthly coaching review": {"fr":"Entraînement au niveau national, comprend une évaluation mensuelle de coaching","de":"Training auf nationalem Niveau, inklusive monatlicher Coaching-Überprüfung","lb":"Training op nationalem Niveau, enthält monatleche Coaching-Review","nl":"Training op nationaal niveau, inclusief maandelijkse coachingbeoordeling"},
  "What a corporate day looks like": {"fr":"À quoi ressemble une journée d'entreprise","de":"Wie ein Firmenevent aussieht","lb":"Wéi en Firmenevent ausgesäit","nl":"Hoe een bedrijfsdag eruitziet"},
  "Let's plan your team day.": {"fr":"Planifions votre journée d'équipe.","de":"Planen wir Ihren Team-Tag.","lb":"Loosst eis Äre Teamdag plangen.","nl":"Laten we uw teamdag plannen."},
  "Tell us how many people, what date, and what you're hoping for. We'll handle the rest.": {"fr":"Dites-nous combien de personnes, quelle date et ce que vous espérez. Nous nous occupons du reste.","de":"Sagen Sie uns, wie viele Personen, welches Datum und was Sie sich erhoffen. Wir erledigen den Rest.","lb":"Sot eis wéivill Leit, wéi eng Datum an wat Dir erhofft. Mir këmmere eis ëm den Rescht.","nl":"Vertel ons hoeveel mensen, welke datum en wat u hoopt. Wij regelen de rest."},
  "Qualified instructors (1:6 ratio)": {"fr":"Instructeurs qualifiés (ratio 1:6)","de":"Qualifizierte Instruktoren (Verhältnis 1:6)","lb":"Qualifizéiert Instrukteuren (Verhältnis 1:6)","nl":"Gekwalificeerde instructeurs (verhouding 1:6)"},
  "Full flight gear for all participants": {"fr":"Équipement de vol complet pour tous les participants","de":"Vollständige Flugausrüstung für alle Teilnehmer","lb":"Vollständeg Fluchausrüstung fir all Participanten","nl":"Volledige vluchtuitrusting voor alle deelnemers"},
  "Viewing gallery access": {"fr":"Accès galerie de visualisation","de":"Zugang zur Zuschauergalerie","lb":"Zougang zur Zuschauergalérie","nl":"Toegang tot de kijkgalerij"},
  "Post-flight debrief space": {"fr":"Espace de débriefing post-vol","de":"Debriefing-Raum nach dem Flug","lb":"Post-Fluch Debriefing-Raum","nl":"Debriefruimte na de vlucht"},
  "Pre-event briefing packs for participants": {"fr":"Packs de briefing pré-événement pour les participants","de":"Vorab-Briefing-Pakete für Teilnehmer","lb":"Pre-Event Briefing-Päck fir Participanten","nl":"Voorafgaande briefingpakketten voor deelnemers"},
  "What coaching covers": {"fr":"Ce que couvre le coaching","de":"Was Coaching abdeckt","lb":"Wat de Coaching deckt","nl":"Wat coaching omvat"},
  "Meet the coaches →": {"fr":"Rencontrez les coaches →","de":"Coaches kennenlernen →","lb":"Coaches kenneleieren →","nl":"Ontmoet de coaches →"},
  "Rates per 30-minute coaching session": {"fr":"Tarifs par session de coaching de 30 minutes","de":"Tarife pro 30-minütiger Coaching-Session","lb":"Taux pro 30-Minutten Coaching-Session","nl":"Tarieven per coachingsessie van 30 minuten"},
  "Pick a date and duration": {"fr":"Choisissez une date et une durée","de":"Wählen Sie Datum und Dauer","lb":"Wielt Datum an Dauer","nl":"Kies een datum en duur"},
  "Pay online or at reception": {"fr":"Payez en ligne ou à la réception","de":"Online oder an der Rezeption bezahlen","lb":"Online oder un der Rezeptioun bezuelen","nl":"Betaal online of bij de receptie"},
  "Come prepared with a goal": {"fr":"Venez préparé avec un objectif","de":"Kommen Sie vorbereitet mit einem Ziel","lb":"Kommt preparéiert mat engem Ziel","nl":"Kom voorbereid met een doel"},
  "Partnership types": {"fr":"Types de partenariat","de":"Partnerschaftstypen","lb":"Partnerschaftstypen","nl":"Soorten partnerschappen"},
  "Dedicated booking link with partner tracking": {"fr":"Lien de réservation dédié avec suivi partenaire","de":"Dedizierter Buchungslink mit Partner-Tracking","lb":"Dediziéierten Buchungslink mat Partner-Tracking","nl":"Toegewijd boekingslink met partnertracking"},
  "Dedicated contact for all partnership queries": {"fr":"Contact dédié pour toutes les demandes de partenariat","de":"Dedizierter Kontakt für alle Partnerschaftsanfragen","lb":"Dediziéierten Kontakt fir all Partnerschaftsufroe","nl":"Toegewijd contact voor alle partnerschapsvragen"},
  "Reserved slots for partner bookings": {"fr":"Créneaux réservés aux réservations partenaires","de":"Reservierte Slots für Partnerbuchungen","lb":"Reservéiert Sloten fir Partnerbuchungen","nl":"Gereserveerde slots voor partnerboekingen"},
  "Responses within 24 hours": {"fr":"Réponses sous 24 heures","de":"Antworten innerhalb von 24 Stunden","lb":"Äntwerte bannent 24 Stonnen","nl":"Antwoorden binnen 24 uur"},
  "Promotional material available in FR, EN, DE, LU": {"fr":"Matériel promotionnel disponible en FR, EN, DE, LU","de":"Werbematerial verfügbar in FR, EN, DE, LU","lb":"Promotionsmaterial verfügbar op FR, EN, DE, LU","nl":"Promotiemateriaal beschikbaar in FR, EN, DE, LU"},
  "Free session for your team at Luxfly": {"fr":"Session gratuite pour votre équipe chez Luxfly","de":"Kostenlose Session für Ihr Team bei Luxfly","lb":"Gratis Session fir Äert Team bei Luxfly","nl":"Gratis sessie voor uw team bij Luxfly"},
  "What we offer": {"fr":"Ce que nous offrons","de":"Was wir anbieten","lb":"Wat mir ubidden","nl":"Wat we bieden"},
  "We work with": {"fr":"Nous travaillons avec","de":"Wir arbeiten mit","lb":"Mir schaffen mat","nl":"We werken met"},
  "Become a partner.": {"fr":"Devenez partenaire.","de":"Werden Sie Partner.","lb":"Gitt Partner.","nl":"Word partner."},
  "Luxembourg City Tourist Office · Selected 4-star hotels in Luxembourg · Kirchberg corporate campus employers · Grand Duchy school networks": {"fr":"Office du tourisme de Luxembourg Ville · Hôtels 4 étoiles sélectionnés · Employeurs du campus Kirchberg · Réseaux scolaires du Grand-Duché","de":"Luxemburg Stadt Touristenbüro · Ausgewählte 4-Sterne-Hotels · Kirchberg Campus Arbeitgeber · Großherzogtum Schulnetzwerke","lb":"Lëtzebuerg Stad Tourismus-Büro · Ausgewielt 4-Stären-Hotellen · Kirchberg Campus Aarbeitgeber · Groussherzogtum Schoulnetzwierker","nl":"Luxembourg Stad Toeristenbureau · Geselecteerde 4-sterrenhotels · Kirchberg campus werkgevers · Schoolnetwerken Groothertogdom"},
  "Good quality 3-star hotels in the city and surrounding towns. Strong value. Family-friendly options available.": {"fr":"Hôtels 3 étoiles de bonne qualité en ville et dans les environs. Bon rapport qualité-prix. Options familiales disponibles.","de":"Gute 3-Sterne-Hotels in der Stadt und Umgebung. Starkes Preis-Leistungs-Verhältnis. Familienfreundliche Optionen verfügbar.","lb":"Gutt 3-Stären-Hotellen an der Stad an Ëmgéigend. Gudde Wäert. Familljefrëndlech Optiounen verfügbar.","nl":"Goede 3-sterrenhotels in de stad en omgeving. Goede waarde. Gezinsvriendelijke opties beschikbaar."},
  "Hostel culture is strong in Luxembourg. Well-managed, social, and centrally located. Great for young travellers.": {"fr":"La culture des auberges de jeunesse est forte au Luxembourg. Bien gérées, sociales et bien situées. Idéales pour les jeunes voyageurs.","de":"Die Hostelkultur ist in Luxemburg stark. Gut geführt, sozial und zentral gelegen. Ideal für junge Reisende.","lb":"D'Hostelkultur ass staark a Lëtzebuerg. Gutt geréiert, sozial a zentral gelegen. Super fir jonk Reesender.","nl":"De hostelcultuur is sterk in Luxemburg. Goed beheerd, sociaal en centraal gelegen. Geweldig voor jonge reizigers."},
  "Guesthouses and farm stays in the Ardennes and Moselle valleys. Peaceful, scenic, easy day trip to Luxfly.": {"fr":"Maisons d'hôtes et séjours à la ferme dans les Ardennes et les vallées de la Moselle. Paisibles, pittoresques, facile d'accès depuis Luxfly.","de":"Gästehäuser und Bauernhofaufenthalte in den Ardennen und Moseltälern. Ruhig, malerisch, einfacher Tagesausflug zu Luxfly.","lb":"Gästehaiser a Bauernhofbleiwen an den Ardennen a Moseltäler. Roueg, pittoresk, einfachen Dagesausflug zu Luxfly.","nl":"Gasthuizen en boerderijverblijven in de Ardennen en Moezelvalleien. Rustig, schilderachtig, gemakkelijke dagtocht naar Luxfly."},
  "Luxembourg City is compact, walkable, and built on dramatic elevation changes. The Old Town is UNESCO-listed. Medieval fortifications rise above the Alzette River. Museums, galleries, cafes, and restaurants fill the narrow streets.": {"fr":"Luxembourg-Ville est compacte, praticable à pied et construite sur des changements d'altitude spectaculaires. La vieille ville est classée UNESCO. Des fortifications médiévales s'élèvent au-dessus de la rivière Alzette. Musées, galeries, cafés et restaurants remplissent les ruelles.","de":"Luxemburg Stadt ist kompakt, fußgängerfreundlich und auf dramatischen Höhenunterschieden gebaut. Die Altstadt ist UNESCO-gelistet. Mittelalterliche Befestigungen erheben sich über dem Fluss Alzette.","lb":"Lëtzebuerg Stad ass kompakt, ze Fouss begehbar a gebaut op dramatischen Héichtvariatiounen. D'Altstad ass UNESCO-gelistet.","nl":"Luxemburg Stad is compact, beloopbaar en gebouwd op dramatische hoogteverschillen. De oude stad staat op de UNESCO-lijst. Middeleeuwse versterkingen rijzen op boven de Alzette-rivier."},
  "The Moselle wine region is 30 minutes south. The Ardennes forest and Vianden Castle are accessible from Luxembourg. Belgium and Germany are close — day trips are straightforward.": {"fr":"La région viticole de la Moselle est à 30 minutes au sud. La forêt des Ardennes et le château de Vianden sont accessibles depuis le Luxembourg. La Belgique et l'Allemagne sont proches.","de":"Die Mosel-Weinregion ist 30 Minuten südlich. Der Ardennenwald und Schloss Vianden sind von Luxemburg aus zugänglich. Belgien und Deutschland sind nah.","lb":"D'Mosel-Wengert ass 30 Minutten südlech. D'Ardennewalde a Veianen Schlass sinn vun Lëtzebuerg aus zugänglech. Belgien an Däitschland sinn no.","nl":"Het Moezel wijngebied is 30 minuten naar het zuiden. Het Ardennen woud en kasteel Vianden zijn bereikbaar vanuit Luxemburg. België en Duitsland zijn dichtbij."},
  "Luxfly fits naturally into a longer exploration of the greater region.": {"fr":"Luxfly s'intègre naturellement dans une exploration plus longue de la grande région.","de":"Luxfly passt natürlich in eine längere Erkundung der Großregion.","lb":"Luxfly passt natierlech an eng längere Erkundung vun der Groussregioun.","nl":"Luxfly past van nature in een langere verkenning van de Grootregio."},
  "Float above the Moselle Valley at sunrise. Gentle, serene, and completely different from freefall.": {"fr":"Flottez au-dessus de la vallée de la Moselle au lever du soleil. Doux, serein et complètement différent de la chute libre.","de":"Schweben Sie bei Sonnenaufgang über das Moseltal. Sanft, ruhig und völlig anders als Freifall.","lb":"Schwiewt iwwert d'Moseltall beim Sonnenopgang. Sanft, roueg a komplett aners wéi Fräifall.","nl":"Zweef boven de Moezelstee bij zonsopgang. Zacht, sereen en totaal anders dan vrije val."},
  "Flights operate spring through autumn, weather permitting. Early mornings are preferred for stable conditions.": {"fr":"Les vols se déroulent du printemps à l'automne, selon la météo. Les matins tôt sont privilégiés pour des conditions stables.","de":"Flüge finden Frühling bis Herbst statt, wetterabhängig. Frühmorgendliche Starts werden für stabile Bedingungen bevorzugt.","lb":"Flëg fanne Fréijoer bis Hierscht statt, no Wieder. Fréimatinnen ginn fir stabil Bedingungen bevorzugt.","nl":"Vluchten vinden plaats van lente tot herfst, weersafhankelijk. Vroege ochtenden worden de voorkeur gegeven voor stabiele omstandigheden."},
  "Includes champagne breakfast and transfer from Luxfly": {"fr":"Comprend petit-déjeuner champagne et transfert depuis Luxfly","de":"Beinhaltet Champagner-Frühstück und Transfer von Luxfly","lb":"Enthält Champagner-Frühstück an Transfer vu Luxfly","nl":"Inclusief champagne ontbijt en transfer vanuit Luxfly"},
  "Safe. Certified. Tested.": {"fr":"Sûr. Certifié. Testé.","de":"Sicher. Zertifiziert. Getestet.","lb":"Sécher. Zertifizéiert. Getest.","nl":"Veilig. Gecertificeerd. Getest."},
  "Padded walls throughout the flying zone": {"fr":"Murs rembourrés dans toute la zone de vol","de":"Gepolsterte Wände in der gesamten Flugzone","lb":"Gepolstert Wänn duerch déi ganzen Fluchzone","nl":"Beklede muren door de hele vliegzone"},
  "Emergency stop accessible by both instructor and operator": {"fr":"Arrêt d'urgence accessible par l'instructeur et l'opérateur","de":"Notausschalter zugänglich für Instruktor und Bediener","lb":"Noutausschalter zugänglech fir Instrukter an Operateur","nl":"Noodstop toegankelijk voor zowel instructeur als operator"},
  "Independent overload protection on each motor": {"fr":"Protection contre les surcharges indépendante sur chaque moteur","de":"Unabhängiger Überlastschutz auf jedem Motor","lb":"Onofhängege Iwwerlaschtschutz op all Motor","nl":"Onafhankelijke overbelastingsbeveiliging op elke motor"},
  "Video recording built in — all sessions recorded": {"fr":"Enregistrement vidéo intégré — toutes les sessions enregistrées","de":"Videoaufzeichnung integriert — alle Sessions aufgezeichnet","lb":"Videoopnahm integréiert — all Sessionen opgeholl","nl":"Ingebouwde video-opname — alle sessies opgenomen"},
  "Instructors have child-flight certification": {"fr":"Les instructeurs ont une certification de vol pour enfants","de":"Instruktoren haben Kinderflugsicherung","lb":"Instrukteuren hunn Kannerflugsertifikat","nl":"Instructeurs hebben kindervluchcertificering"},
  "Minimum age 4": {"fr":"Âge minimum 4 ans","de":"Mindestalter 4 Jahre","lb":"Mindestalter 4 Joer","nl":"Minimumleeftijd 4 jaar"},
  "Kids under age 4 cannot fly, but are welcome to watch from our viewing area. We have age-appropriate safety considerations for all health conditions.": {"fr":"Les enfants de moins de 4 ans ne peuvent pas voler mais sont les bienvenus pour regarder depuis notre zone de visualisation.","de":"Kinder unter 4 Jahren können nicht fliegen, sind aber willkommen, von unserem Zuschauerbereich aus zuzusehen.","lb":"Kanner ënner 4 Joer kënnen net fléien mee si wëllkommen aus eisem Kuckberäich ze kucken.","nl":"Kinderen jonger dan 4 jaar kunnen niet vliegen, maar zijn welkom om te kijken vanuit ons kijkgebied."},
  "Short and fun for first-timers, longer sessions for those who want more air time": {"fr":"Court et amusant pour les débutants, sessions plus longues pour ceux qui veulent plus de temps de vol","de":"Kurz und spaßig für Erstflügler, längere Sessions für die, die mehr Flugzeit wollen","lb":"Kuerz a spasseg fir Éiertfliger, längere Sessionen fir déi déi méi Fluchzäit wëllen","nl":"Kort en leuk voor beginners, langere sessies voor wie meer vluchtijd wil"},
  "From 5 guests up to large parties — we tailor the session to your numbers": {"fr":"De 5 invités aux grandes fêtes — nous adaptons la session à votre nombre","de":"Von 5 Gästen bis zu großen Partys — wir passen die Session Ihrer Größe an","lb":"Vun 5 Gäscht bis zu grousse Partyen — mir passen d'Session un Är Zuel un","nl":"Van 5 gasten tot grote feesten — we passen de sessie aan uw aantallen aan"},
  "From age 4 to 95 — we adjust the session for kids, adults, or mixed groups": {"fr":"De 4 à 95 ans — nous adaptons la session pour les enfants, adultes ou groupes mixtes","de":"Von 4 bis 95 Jahren — wir passen die Session für Kinder, Erwachsene oder gemischte Gruppen an","lb":"Vun 4 bis 95 Joer — mir passen d'Session fir Kanner, Erwuessener oder gemëscht Groupe un","nl":"Van 4 tot 95 jaar — we passen de sessie aan voor kinderen, volwassenen of gemengde groepen"},
  "Photos, video highlights, catering, birthday setup — mix and match what you need": {"fr":"Photos, extraits vidéo, traiteur, décoration d'anniversaire — combinez selon vos besoins","de":"Fotos, Video-Highlights, Catering, Geburtstagsausstattung — kombinieren Sie nach Bedarf","lb":"Fotoen, Video-Highlights, Catering, Gebuertsdagssetup — mix a match wat Dir braucht","nl":"Foto's, videohoogtepunten, catering, verjaardagsopstelling — combineer naar behoefte"},
  "Secure your date with a 50% deposit. Balance is due 7 days before the party.": {"fr":"Sécurisez votre date avec un acompte de 50%. Le solde est dû 7 jours avant la fête.","de":"Sichern Sie Ihr Datum mit einer Anzahlung von 50%. Der Restbetrag ist 7 Tage vor der Party fällig.","lb":"Séchert Äert Datum mat engem 50% Depôt. De Reschtbetrag ass 7 Deeg viru der Party fälleg.","nl":"Beveilig uw datum met 50% aanbetaling. Het saldo is 7 dagen voor het feest verschuldigd."},
  "Tell us about yours and we'll put together the right package.": {"fr":"Parlez-nous du vôtre et nous mettrons ensemble le bon forfait.","de":"Erzählen Sie uns von Ihrem und wir stellen das richtige Paket zusammen.","lb":"Erzielt eis vun Ärem an mir setzen zesummen de richtege Pak.","nl":"Vertel ons over het uwe en we stellen het juiste pakket samen."},
  "Custom certificates of completion": {"fr":"Certificats personnalisés d'achèvement","de":"Individuelle Abschlusszertifikate","lb":"Personaliséiert Ofschlossertifikater","nl":"Aangepaste voltooiingscertificaten"},
  "Private briefing room": {"fr":"Salle de briefing privée","de":"Privater Briefing-Raum","lb":"Privat Briefing-Raum","nl":"Privé briefingkamer"},
  "Minimum group: 5 people.": {"fr":"Groupe minimum : 5 personnes.","de":"Mindestgruppe: 5 Personen.","lb":"Mindestgrupp: 5 Persounen.","nl":"Minimale groep: 5 personen."},
  "No golf. No paint guns. Just 350 km/h of genuine madness. You're welcome.": {"fr":"Pas de golf. Pas de pistolets à peinture. Juste 350 km/h de vraie folie. De rien.","de":"Kein Golf. Keine Farbpistolen. Nur 350 km/h echten Wahnsinns. Bitte sehr.","lb":"Kee Golf. Keng Faarfpistoulen. Just 350 km/h vu wierklecht Wahnsinn. Gär geschitt.","nl":"Geen golf. Geen verfpistolen. Gewoon 350 km/u pure waanzin. Graag gedaan."},
  "This is the ultimate pre-wedding activity — something everyone will actually remember. It works for groups of 6 to 30 people. Your stag or hen gets extra coaching attention and walks away with a certificate on the day. And then you all go to the bar and celebrate properly.": {"fr":"C'est l'activité ultime avant le mariage — quelque chose dont tout le monde se souviendra vraiment. Pour les groupes de 6 à 30 personnes. Votre futur marié ou mariée bénéficie d'une attention de coaching supplémentaire.","de":"Das ist die ultimative Vorhochzeitsaktivität — etwas, an das sich wirklich alle erinnern werden. Für Gruppen von 6 bis 30 Personen.","lb":"Dat ass déi ultimativ Pre-Hochzeitsaktivitéit — eppes un dat sech jiddereen wierklech erënnert. Fir Gruppe vun 6 bis 30 Persounen.","nl":"Dit is de ultieme activiteit voor het huwelijk — iets waar iedereen echt aan zal denken. Voor groepen van 6 tot 30 mensen."},
  "What Kind of Flyer Are You?": {"fr":"Quel type de pilote êtes-vous ?","de":"Was für ein Flieger sind Sie?","lb":"Wat fir e Fléier sidd Dir?","nl":"Wat voor vlieger bent u?"},
  "Health & fitness requirements": {"fr":"Exigences de santé et de forme","de":"Gesundheits- und Fitnessanforderungen","lb":"Gesondheetsufuerderungen","nl":"Gezondheids- en fitnessvereisten"},
  "Health notes": {"fr":"Notes de santé","de":"Gesundheitshinweise","lb":"Gesondheetshinweiser","nl":"Gezondheidsopmerkingen"},
  "Liability & waivers": {"fr":"Responsabilité & renonciations","de":"Haftung & Freistellungen","lb":"Haftung & Verzichtserkläerungen","nl":"Aansprakelijkheid & vrijwaringen"},
  "House rules & facility guidelines": {"fr":"Règles de la maison & directives des installations","de":"Hausregeln & Einrichtungsrichtlinien","lb":"Hausregelen & Anlagenrichtlinien","nl":"Huisregels & faciliteitrichtlijnen"},
  "No alcohol or recreational substances before flying": {"fr":"Pas d'alcool ni de substances récréatives avant de voler","de":"Kein Alkohol oder Freizeitmittel vor dem Fliegen","lb":"Kee Alkohol oder Freizäitmëttelen virum Fléien","nl":"Geen alcohol of recreatieve middelen voor het vliegen"},
  "No food or drink inside the tunnel or gear room (water bottle in waiting area is fine)": {"fr":"Pas de nourriture ni de boisson dans le tunnel ou la salle d'équipement (bouteille d'eau dans la salle d'attente est acceptable)","de":"Kein Essen oder Trinken im Tunnel oder Ausrüstungsraum (Wasserflasche im Wartebereich ist in Ordnung)","lb":"Kee Iessen oder Gedrénks am Tunnel oder Ausrüstungsraum (Waasserfläsch am Waardraum ass ok)","nl":"Geen eten of drinken in de tunnel of uitrustingsruimte (waterfles in wachtruimte is prima)"},
  "Smoking is prohibited throughout the facility": {"fr":"Il est interdit de fumer dans toute l'installation","de":"Rauchen ist in der gesamten Anlage verboten","lb":"Rauchen ass an der ganzer Anlage verbueden","nl":"Roken is verboden in de gehele faciliteit"},
  "No personal photography inside the tunnel (professional photos available)": {"fr":"Pas de photographie personnelle dans le tunnel (photos professionnelles disponibles)","de":"Keine persönliche Fotografie im Tunnel (professionelle Fotos verfügbar)","lb":"Keng perséinlech Fotografie am Tunnel (professionell Fotoen verfügbar)","nl":"Geen persoonlijke fotografie in de tunnel (professionele foto's beschikbaar)"},
  "Follow instructions exactly and ask questions": {"fr":"Suivez les instructions exactement et posez des questions","de":"Anweisungen genau befolgen und Fragen stellen","lb":"Instruktioune genau befolgen a Froen stellen","nl":"Volg instructies exact op en stel vragen"},
  "Do not attempt tricks or moves not approved by your instructor": {"fr":"N'essayez pas de tours ou de mouvements non approuvés par votre instructeur","de":"Versuchen Sie keine Tricks oder Bewegungen, die nicht von Ihrem Instruktor genehmigt wurden","lb":"Versicht keng Tricks oder Bewegungen déi net vun Ärem Instrukter genehmegt goufen","nl":"Probeer geen trucs of bewegingen die niet door uw instructeur zijn goedgekeurd"},
  "Report any physical discomfort or concern immediately to your instructor": {"fr":"Signalez immédiatement tout inconfort physique ou préoccupation à votre instructeur","de":"Melden Sie jegliche körperliche Beschwerden oder Bedenken sofort Ihrem Instruktor","lb":"Mellt all kierperleche Beschwerden oder Bedenken direkt Ärem Instrukter","nl":"Meld elke fysieke ongemak of zorg onmiddellijk aan uw instructeur"},
  "What to wear & bring": {"fr":"Quoi porter et apporter","de":"Was tragen und mitbringen","lb":"Wat undoen a matbréngen","nl":"Wat te dragen en mee te brengen"},
  "Jeans, leggings, or tracksuit bottoms": {"fr":"Jeans, leggings ou pantalon de survêtement","de":"Jeans, Leggings oder Trainingshose","lb":"Jeans, Leggings oder Jogginghos","nl":"Jeans, legging of trainingsbroek"},
  "Wear comfortable, close-fitting clothes. Jeans, leggings, tracksuit bottoms all work. Hair should be tied back if longer than shoulder-length. Wear lace-up shoes or trainers.": {"fr":"Portez des vêtements confortables et ajustés. Jeans, leggings, bas de survêtement conviennent tous. Les cheveux doivent être attachés s'ils dépassent les épaules. Portez des chaussures à lacets ou des baskets.","de":"Tragen Sie bequeme, eng anliegende Kleidung. Jeans, Leggings, Jogginghosen funktionieren alle. Haare sollten zurückgebunden werden, wenn länger als Schulterlänge.","lb":"Draagt komfortabel, noleeend Kleeder. Jeans, Leggings, Jogginghosen passt all. Hoer soll zrëckgebonnen sinn wann längert wéi Schulterlängt.","nl":"Draag comfortabele, strakke kleding. Jeans, leggings, trainingsbroek werken allemaal. Haar moet worden teruggebonden als het langer is dan schouderlang."},
  "Don't wear into the tunnel": {"fr":"Ne portez pas dans le tunnel","de":"Nicht in den Tunnel tragen","lb":"Net an den Tunnel droen","nl":"Niet de tunnel in dragen"},
  "Don't wear:": {"fr":"Ne portez pas :","de":"Nicht tragen:","nl":"Niet dragen:","lb":"Net unzéien:"},
  "Watches or bulky rings": {"fr":"Montres ou bagues volumineuses","de":"Uhren oder klobige Ringe","lb":"Aieren oder klumpeg Réng","nl":"Horloges of omvangrijke ringen"},
  "Loose jewellery or accessories": {"fr":"Bijoux ou accessoires amples","de":"Lose Schmuckstücke oder Zubehör","lb":"Lose Bijouterien oder Accessoiren","nl":"Los sieraad of accessoires"},
  "Hats or hoods (not secured)": {"fr":"Chapeaux ou capuches (non sécurisés)","de":"Hüte oder Kapuzen (nicht gesichert)","lb":"Hütt oder Kapuzen (net sécher)","nl":"Hoeden of capuchons (niet vastgemaakt)"},
  "Loose items in pockets — remove everything before entry": {"fr":"Objets amples dans les poches — retirez tout avant l'entrée","de":"Lose Gegenstände in Taschen — alles vor dem Eingang entfernen","lb":"Lose Saachen a Täschen — alles virum Eintritt ewech huelen","nl":"Losse voorwerpen in zakken — verwijder alles voor binnenkomst"},
  "Loose jewellery or hair clips": {"fr":"Bijoux amples ou barrettes","de":"Lose Schmuckstücke oder Haarklammern","lb":"Lose Bijouterien oder Hoerklammer","nl":"Los sieraad of haarspeldjes"},
  "Glasses (contacts are fine)": {"fr":"Lunettes (les verres de contact sont acceptables)","de":"Brille (Kontaktlinsen sind in Ordnung)","lb":"Brëller (Kontaktlinsen sinn ok)","nl":"Bril (contactlenzen zijn prima)"},
  "We provide secure lockers for your valuables. Professional photography is available if you want photos of your flight.": {"fr":"Nous fournissons des casiers sécurisés pour vos objets de valeur. La photographie professionnelle est disponible si vous souhaitez des photos de votre vol.","de":"Wir stellen sichere Schließfächer für Ihre Wertsachen bereit. Professionelle Fotografie ist verfügbar, wenn Sie Fotos von Ihrem Flug möchten.","lb":"Mir bidden sécher Schafcher fir Är Wäertsaachen. Professionell Fotografie ass verfügbar wann Dir Fotoen vun Ärem Fluch wëllt.","nl":"We bieden veilige kluisjes voor uw waardevolle spullen. Professionele fotografie is beschikbaar als u foto's van uw vlucht wilt."},
  "Your body floats. Your mind goes quiet. The only thing you feel is the rush of wind on your face and the sensation of weightlessness that most people experience only once in their lifetime — in a skydive. But here, you can have that feeling again and again.": {"fr":"Votre corps flotte. Votre esprit se calme. La seule chose que vous ressentez est le souffle du vent sur votre visage et la sensation d'apesanteur que la plupart des gens n'expérimentent qu'une fois dans leur vie.","de":"Ihr Körper schwebt. Ihr Geist wird still. Das Einzige, was Sie fühlen, ist der Windstrom auf Ihrem Gesicht und das Gefühl der Schwerelosigkeit, das die meisten Menschen nur einmal erleben.","lb":"Äre Kierper schwiewt. Äre Geescht gëtt roueg. Dat eenzegt wat Dir spiert ass den Drang vum Wand op Ärem Gesiicht.","nl":"Uw lichaam zweeft. Uw geest wordt stil. Het enige wat u voelt is de windstoot op uw gezicht en de gewichtloosheid die de meeste mensen slechts één keer in hun leven ervaren."},
  "Quick answers": {"fr":"Réponses rapides","de":"Schnelle Antworten","lb":"Séier Äntwerten","nl":"Snelle antwoorden"},
  "Not sure yet?": {"fr":"Pas encore sûr ?","de":"Noch nicht sicher?","lb":"Nach net sécher?","nl":"Nog niet zeker?"},
  "Ready to come?": {"fr":"Prêt à venir ?","de":"Bereit zu kommen?","lb":"Prett fir ze kommen?","nl":"Klaar om te komen?"},
  "Ready to find out what it feels like?": {"fr":"Prêt à découvrir ce que c'est ?","de":"Bereit herauszufinden, wie es sich anfühlt?","lb":"Prett erauszefannen wéi et sech fillt?","nl":"Klaar om uit te vinden hoe het voelt?"},
  "Ready to fly?": {"fr":"Prêt à voler ?","de":"Bereit zu fliegen?","lb":"Prett fir ze fléien?","nl":"Klaar om te vliegen?"},
  "Ready to get a precise quote?": {"fr":"Prêt à obtenir un devis précis ?","de":"Bereit für ein genaues Angebot?","lb":"Prett fir en geneet Offert ze kréien?","nl":"Klaar voor een nauwkeurige offerte?"},
  "Ready to get serious?": {"fr":"Prêt à passer au sérieux ?","de":"Bereit, es ernst zu nehmen?","lb":"Prett fir ernscht ze ginn?","nl":"Klaar om serieus te worden?"},
  "Ready to give the gift?": {"fr":"Prêt à offrir le cadeau ?","de":"Bereit, das Geschenk zu geben?","lb":"Prett fir de Kaddo ze ginn?","nl":"Klaar om het cadeau te geven?"},
  "Ready to start?": {"fr":"Prêt à commencer ?","de":"Bereit anzufangen?","lb":"Prett fir unzefänken?","nl":"Klaar om te beginnen?"},
  "Things to combine with Luxfly": {"fr":"Choses à combiner avec Luxfly","de":"Dinge, die man mit Luxfly kombinieren kann","lb":"Saachen déi mat Luxfly kombinéiert kënne ginn","nl":"Dingen om te combineren met Luxfly"},
  "See packages →": {"fr":"Voir les forfaits →","de":"Pakete ansehen →","lb":"Pakete kucken →","nl":"Pakketten bekijken →"},
  "View menu →": {"fr":"Voir le menu →","de":"Menü ansehen →","lb":"Menü kucken →","nl":"Menu bekijken →"},
  "View pricing →": {"fr":"Voir les prix →","de":"Preise ansehen →","lb":"Präisser kucken →","nl":"Prijzen bekijken →"},
  "See pro pricing →": {"fr":"Voir les tarifs pro →","de":"Pro-Preise ansehen →","lb":"Pro-Präisser kucken →","nl":"Pro-prijzen bekijken →"},
  "Plan your event →": {"fr":"Planifier votre événement →","de":"Event planen →","lb":"Event plangen →","nl":"Uw evenement plannen →"},
  "Photo options →": {"fr":"Options photo →","de":"Fotooptionen →","lb":"Fotooptiounen →","nl":"Foto-opties →"},
  "Group visits →": {"fr":"Visites de groupe →","de":"Gruppenbesuche →","lb":"Gruppevisitten →","nl":"Groepsbezoeken →"},
  "Explore birthdays →": {"fr":"Explorer les anniversaires →","de":"Geburtstage entdecken →","lb":"Gebuertsdagsfeieren entdecken →","nl":"Verjaardagen verkennen →"},
  "See full opening hours →": {"fr":"Voir les heures d'ouverture complètes →","de":"Alle Öffnungszeiten →","lb":"All Ouessungszäiten →","nl":"Alle openingstijden →"},
  "Shared session schedule →": {"fr":"Calendrier des sessions partagées →","de":"Geteilter Sessionplan →","lb":"Gedeelte Sessionplang →","nl":"Gedeeld sessieschema →"},
  "Manage upcoming bookings": {"fr":"Gérer les réservations à venir","de":"Bevorstehende Buchungen verwalten","lb":"Kommend Buchungen verwalten","nl":"Aankomende boekingen beheren"},
  "View and download your flight videos": {"fr":"Voir et télécharger vos vidéos de vol","de":"Flugvideos ansehen und herunterladen","lb":"Fluchvideoen kucken an eroflueden","nl":"Vliegvideo's bekijken en downloaden"},
  "Log in to view your flight history, access your videos, manage bookings, and track your progress over time.": {"fr":"Connectez-vous pour voir votre historique de vols, accéder à vos vidéos, gérer les réservations et suivre votre progression.","de":"Melden Sie sich an, um Ihre Flughistorie zu sehen, auf Ihre Videos zuzugreifen, Buchungen zu verwalten und Ihren Fortschritt zu verfolgen.","lb":"Loggt Iech an fir Är Fluchgeschicht ze gesinn, op Är Videoen zouzegräifen, Buchungen ze verwalten an Ären Fortschrëtt ze verfollegen.","nl":"Log in om uw vluchtgeschiedenis te bekijken, uw video's te openen, boekingen te beheren en uw voortgang bij te houden."},
  "Sign In": {"fr":"Se connecter","de":"Anmelden","lb":"Umellen","nl":"Inloggen"},
  "Your Luxfly account": {"fr":"Votre compte Luxfly","de":"Ihr Luxfly-Konto","lb":"Äre Luxfly-Kont","nl":"Uw Luxfly-account"},
  "Track your tunnel time and progression": {"fr":"Suivez votre temps de tunnel et votre progression","de":"Verfolgen Sie Ihre Tunnelzeit und Ihren Fortschritt","lb":"Verfollegt Är Tunnelzäit an Ären Fortschrëtt","nl":"Houd uw tunneltijd en voortgang bij"},
  "© 2026 Luxfly Indoor Skydiving": {"fr":"© 2026 Luxfly Indoor Skydiving","de":"© 2026 Luxfly Indoor Skydiving","lb":"© 2026 Luxfly Indoor Skydiving","nl":"© 2026 Luxfly Indoor Skydiving"},
}


def inject(content, lang, entries):
    new_lines = [f"      // ── FINAL {lang.upper()} ──"]
    for en, t in entries.items():
        if lang not in t: continue
        val = t[lang]
        ek = en.replace('\\','\\\\').replace("'","\\'")
        vk = val.replace('\\','\\\\').replace("'","\\'")
        new_lines.append(f"      '{ek}': '{vk}',")
    block = '\n' + '\n'.join(new_lines) + '\n'
    pats = {
        'fr': r"(    fr:\s*\{)(.*?)(    \},\s*\n\s*de:)",
        'de': r"(    de:\s*\{)(.*?)(    \},\s*\n\s*lb:)",
        'lb': r"(    lb:\s*\{)(.*?)(    \},\s*\n\s*nl:)",
        'nl': r"(    nl:\s*\{)(.*?)(    \}[^,])",
    }
    m = re.search(pats[lang], content, re.DOTALL)
    if not m:
        print(f"  ERROR: {lang} block not found"); return content
    return content[:m.start()] + m.group(1) + m.group(2) + block + '    ' + m.group(3).lstrip() + content[m.end():]


with open('/Users/zoomzoom/workspace/Luxfly Website/js/i18n.js') as f:
    content = f.read()

for lang in ['fr','de','lb','nl']:
    content = inject(content, lang, T)
    print(f"  {lang} done")

with open('/Users/zoomzoom/workspace/Luxfly Website/js/i18n.js','w') as f:
    f.write(content)

print("Done. Lines:", content.count('\n'))
